# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: inudoption-service

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

# The `functions` block defines what code to deploy
functions:
  inudoption:
    handler: handler.inudoption
    events:
      - http:
          path: pets
          method: get
          cors: true
